name: Windows Build
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: windows-2019
    name: Windows Server 2019

    steps:
      - uses: actions/checkout@v2

      - name: Configure Windows
        run: choco install --no-progress openssl

      - name: Checkout Submodules
        shell: bash
        run: apps/ci/ci-submodule-update.sh

      - name: Build Project
        shell: bash
        run: .github/workflows/core_windows_build.yml
